export const TITLES = {
  '/': 'Home - NextSeed',
  '/offerings/': 'Browser - NextSeed Investment Opportunities',
  '/business/how-it-works': 'Business | How it works - NextSeed',
  '/business/funding-options/term-notes': 'Business | Funding Options | Term Notes - NextSeed',
  '/business/funding-options/revenue-sharing-notes': 'Business | Funding Options | Revenue Sharing Notes - NextSeed',
  '/business/funding-options/preferred-equity': 'Business | Funding Options | Preferred Equity - NextSeed',
  '/business/process': 'Business | Process - NextSeed',
  '/business/all-inclusive': 'Business | All Inclusive - NextSeed',
  '/invest/why-nextseed': 'Invest | Why Nextseed - NextSeed',
  '/invest/how-it-works': 'Invest | How It Works - NextSeed',
  '/invest/account-types': 'Invest | Account Types - NextSeed',
  '/invest/security': 'Invest | Security - NextSeed',
  '/invest/track': 'Invest | Track - NextSeed',
  '/about/mission': 'About | Mission - NextSeed',
  '/about/team': 'About | Team - NextSeed',
  '/about/careers': 'About | Careers - NextSeed',
  '/resources/insights': 'Resources | Insights - NextSeed',
  '/resources/education-center': 'Resources | Education Center - NextSeed',
  '/resources/education-center/investor': 'Resources | Education Center | Investors - NextSeed',
  '/resources/education-center/business': 'Resources | Education Center | Business - NextSeed',
  '/agreements/legal/terms-of-use': 'Agreements | Terms of use - NextSeed',
  '/agreements/legal/privacy-policy': 'Agreements | Privacy policy - NextSeed',
  '/agreements/legal/general-disclosures': 'Agreements | General disclosures - NextSeed',
  '/agreements/legal/general-risk-factors': 'Agreements | General risk factors - NextSeed',
  '/agreements/legal/legal-documents': 'Agreements | Legal documents - NextSeed',
  '/login': 'Log in to NextSeed',
  '/register': 'Join the NextSeed community',
  '/forgot-password': 'Reset your password - NextSeed',
  '/register-investor': 'Join the NextSeed community | Sign up as an Investor',
  '/business-application/business': 'Join the NextSeed community | Pre-Qualification Application Process',
  '/business-application/commercial-real-estate': 'Join the NextSeed community | Pre-Qualification Application Process',
  '/business-application/questions/need-help': 'Join the NextSeed community | Pre-Qualification Application Process | Need Help',
};
