export const ACCREDITATION_FILE_UPLOAD_ENUMS = {
  incomeDocSecondLastYear: 'PROFILE_ACCREDITATION_2016_INCOME',
  incomeDocLastYear: 'PROFILE_ACCREDITATION_2017_INCOME',
  statementDoc: 'PROFILE_ACCREDITATION_ASSETS',
};

export const ACCREDITATION_METHOD_ENUMS = {
  INCOME: 'Income',
  ASSETS: 'Assets',
  REVOCABLE_TRUST_ASSETS: 'Trust Assets',
  REVOCABLE_TRUST_INCOME: 'Trust Income',
  OWNERS_ACCREDITATED: 'Entity Owners Accredited',
  OWNERS_QUALIFIED: 'Entity Owners Qualified',
};

export const ACCREDITATION_NETWORTH_LABEL = {
  FIVE_MILLION: '$5,000,000',
  TWENTY_FIVE_MILLION: '$25,000,000',
  TWO_MILLION: '$2,000,000',
  ONE_MILLION: '$1,000,000',
};
