export const ACCREDITATION_FILE_UPLOAD_ENUMS = {
  individual: 'PROFILE_ACCREDITATION_INDIVIDUAL_IRA_PROCESSING',
  ira: 'PROFILE_ACCREDITATION_INDIVIDUAL_IRA_PROCESSING',
  entity: 'PROFILE_ACCREDITATION_ENTITY_PROCESSING',
};

export const ACCREDITATION_APPROVE_DECLINE_FILE_UPLOAD_ENUMS = {
  individual: 'PROFILE_ACCREDITATION_APPROVE_DECLINE_INDIVIDUAL_IRA',
  ira: 'PROFILE_ACCREDITATION_APPROVE_DECLINE_INDIVIDUAL_IRA',
  entity: 'PROFILE_ACCREDITATION_APPROVE_DECLINE_ENTITY',
};

export const UPLOAD_ASSET_ENUMS = {
  statementDoc: 'ASSETS',
  incomeDocSecondLastYear: 'INCOME_2017',
  incomeDocLastYear: 'INCOME_2018',
  incomeDocThirdLastYear: 'INCOME_2016',
};

export const ACCREDITATION_METHOD_ENUMS = {
  INCOME: 'Income',
  ASSETS: 'Assets',
  REVOCABLE_TRUST_ASSETS: 'Trust Assets',
  REVOCABLE_TRUST_INCOME: 'Trust Income',
  OWNERS_ACCREDITATED: 'Entity Owners Accredited',
  OWNERS_QUALIFIED: 'Entity Owners Qualified',
};

export const ACCREDITATION_NETWORTH_LABEL = {
  FIVE_MILLION: '$5,000,000',
  TWENTY_FIVE_MILLION: '$25,000,000',
  TWO_MILLION: '$2,000,000',
  ONE_MILLION: '$1,000,000',
};
