export const ACCREDITATION_FILE_UPLOAD_ENUMS = {
  incomeDocSecondLastYear: 'PROFILE_ACCREDITATION_2016_INCOME',
  incomeDocLastYear: 'PROFILE_ACCREDITATION_2017_INCOME',
  statementDoc: 'PROFILE_ACCREDITATION_ASSETS',
};
