export const TEAM = {
  title: {
    value: '', label: 'Title', placeHolder: 'Title', error: undefined, rule: 'required',
  },
  memberName: {
    value: '', label: 'Member Name', placeHolder: 'Member Name', error: undefined, rule: 'required',
  },
  story: {
    value: '', label: '', error: undefined, rule: 'optional', placeHolder: 'Describe the story of the ambassador',
  },
  order: {
    value: null, label: 'Order', placeHolder: 'Order', error: undefined, rule: 'optional',
  },
  // status: {
  //   value: '', label: 'Status', error: undefined, rule: 'optional',
  // },
  // avatar: {
  //   value: '', label: 'Avatar', error: undefined, rule: 'optional',
  // },
  avatar: {
    value: '',
    key: 'avatar',
    error: undefined,
    fileName: '',
    rule: 'optional',
    label: 'Avatar',
    src: '',
    base64String: '',
    responseUrl: '',
    fileData: '',
    meta: {},
    objRef: 'uploads',
    objType: 's3File',
    objRefOutput2: 'uploads',
  },
  heroImage: {
    value: '',
    key: 'heroImage',
    error: undefined,
    fileName: '',
    rule: 'optional',
    label: 'Hero Image',
    src: '',
    base64String: '',
    responseUrl: '',
    fileData: '',
    meta: {},
    objRef: 'uploads',
    objType: 's3File',
    objRefOutput2: 'uploads',
  },
  // heroImage: {
  //   value: '', label: 'Hero Image', error: undefined, rule: 'optional',
  // },
  facebook: {
    value: '',
    label: 'Facebook',
    error: undefined,
    rule: 'optional',
    placeHolder: 'Paste Facebook profile URL',
    objRef: 'offering.overview.social',
    find: 'type',
    type: 'facebook',
    skipField: true,
    ArrayObjItem: true,
  },
  linkedin: {
    value: '',
    label: 'LinkedIn',
    error: undefined,
    rule: 'optional',
    placeHolder: 'Paste LinkedIn profile URL',
    // objRef: 'offering.overview.social',
    find: 'type',
    type: 'linkedin',
    skipField: true,
    ArrayObjItem: true,
  },
  twitter: {
    value: '',
    label: 'Twitter',
    error: undefined,
    rule: 'optional',
    placeHolder: 'Paste Twitter profile URL',
    // objRef: 'offering.overview.social',
    find: 'type',
    skipField: true,
    type: 'twitter',
    ArrayObjItem: true,
  },
  instagram: {
    value: '',
    label: 'Instagram',
    error: undefined,
    rule: 'optional',
    placeHolder: 'Paste omstagra, profile URL',
    // objRef: 'offering.overview.social',
    find: 'type',
    skipField: true,
    type: 'instagram',
    ArrayObjItem: true,
  },
};
